App\Entity\Client:
    properties:
        name:
            - NotBlank: ~
        accountNumber:
            - NotBlank: ~
            - Length:
                min: 8
                max: 34
        email:
            - NotBlank: ~
            - Email:
                message: The email "{{ value }}" is not valid.
        phoneNumber:
            - NotBlank: ~

App\Entity\Money:
    properties:
        client:
            - NotBlank: ~