controllers:
    resource: ../src/Controller/
    type: attribute

# =================================================================

client_list:
    path: /api/client
    controller: App\Controller\ClientController::indexAction
    methods: [GET]

client_show:
    path: /api/client/{clientId}
    controller: App\Controller\ClientController::showAction
    methods: [GET]
    requirements:
        id: '\d+'

client_create:
    path: /api/client
    controller: App\Controller\ClientController::createAction
    methods: [POST]

client_update:
    path: /api/client/{clientId}
    controller: App\Controller\ClientController::updateAction
    methods: [PATCH]
    requirements:
        id: '\d+'

client_delete:
    path: /api/client/{clientId}
    controller: App\Controller\ClientController::deleteAction
    methods: [DELETE]
    requirements:
        id: '\d+'

# =================================================================

money_list:
    path: /api/money/{clientId}/money
    controller: App\Controller\MoneyController::indexAction
    methods: [GET]

money_transaction:
    path: /api/money/transaction
    controller: App\Controller\MoneyController::transactionAction
    methods: [POST]

money_balance:
    path: /api/money/{clientId}/balance
    controller: App\Controller\MoneyController::balanceAction
    methods: [GET]
    requirements:
        id: '\d+'

money_history:
    path: /api/money/{clientId}/history
    controller: App\Controller\MoneyController::historyAction
    methods: [GET]
    requirements:
        id: '\d+'