controllers:
    resource: ../src/Controller/
    type: attribute

# =================================================================

client_list:
    path: /api/client
    controller: App\Controller\ClientController::indexAction
    methods: [GET]

client_show:
    path: /api/client/{id}
    controller: App\Controller\ClientController::showAction
    methods: [GET]
    requirements:
        id: '\d+'

client_balance:
    path: /api/client/{id}/balance
    controller: App\Controller\ClientController::balanceAction
    methods: [GET]
    requirements:
        id: '\d+'

client_create:
    path: /api/client
    controller: App\Controller\ClientController::createAction
    methods: [POST]

client_update:
    path: /api/client/{id}
    controller: App\Controller\ClientController::updateAction
    methods: [PATCH]
    requirements:
        id: '\d+'

client_delete:
    path: /api/client/{id}
    controller: App\Controller\ClientController::deleteAction
    methods: [DELETE]
    requirements:
        id: '\d+'

# =================================================================

money_list:
    path: /api/client/{clientId}/money
    controller: App\Controller\MoneyController::indexAction
    methods: [GET]

money_history:
    path: /api/money/{clientId}/history
    controller: App\Controller\MoneyController::historyAction
    methods: [GET]
    requirements:
        id: '\d+'

money_withdraw:
    path: /api/withdraw
    controller: App\Controller\MoneyController::withdrawAction
    methods: [POST]

money_deposit:
    path: /api/deposit
    controller: App\Controller\MoneyController::depositAction
    methods: [POST]